export const getDummyPosts = () => [
  {
    id: 1,
    username: "JohnDoe",
    profileImage: "https://via.placeholder.com/50",
    text: "Exploring the wonders of #React! 🚀",
    image: "https://via.placeholder.com/500",
    hashtags: ["React"],
    likes: 12,
    liked: false,
    comments: [],
    timestamp: "2 hours ago",
  },
  {
    id: 2,
    username: "AliceSmith",
    profileImage: "https://via.placeholder.com/50",
    text: "Building a new #JavaScript project! 💻",
    image: "",
    hashtags: ["JavaScript"],
    likes: 20,
    liked: false,
    comments: [],
    timestamp: "3 hours ago",
  },
  {
    id: 3,
    username: "TechGuru",
    profileImage: "https://via.placeholder.com/50",
    text: "Just finished an awesome #TailwindCSS UI! 🎨",
    image: "https://via.placeholder.com/500",
    hashtags: ["TailwindCSS"],
    likes: 30,
    liked: false,
    comments: [],
    timestamp: "5 hours ago",
  },
  {
    id: 4,
    username: "JaneDoe",
    profileImage: "https://via.placeholder.com/50",
    text: "Loving the #DarkMode feature! 🌙",
    image: "",
    hashtags: ["DarkMode"],
    likes: 5,
    liked: false,
    comments: [],
    timestamp: "1 hour ago",
  },
  {
    id: 5,
    username: "Mark23",
    profileImage: "https://via.placeholder.com/50",
    text: "Backend development with #NodeJS is fun! 🛠️",
    image: "",
    hashtags: ["NodeJS"],
    likes: 18,
    liked: false,
    comments: [],
    timestamp: "6 hours ago",
  },
  {
    id: 6,
    username: "SaraTech",
    profileImage: "https://via.placeholder.com/50",
    text: "Started a new #NextJS project! 🚀",
    image: "",
    hashtags: ["NextJS"],
    likes: 24,
    liked: false,
    comments: [],
    timestamp: "8 hours ago",
  },
  {
    id: 7,
    username: "TomCoder",
    profileImage: "https://via.placeholder.com/50",
    text: "The magic of #AI and #MachineLearning 🤖",
    image: "https://via.placeholder.com/500",
    hashtags: ["AI", "MachineLearning"],
    likes: 35,
    liked: false,
    comments: [],
    timestamp: "10 hours ago",
  },
  {
    id: 8,
    username: "DevOpsKing",
    profileImage: "https://via.placeholder.com/50",
    text: "#Docker and #Kubernetes are game changers! ⚡",
    image: "",
    hashtags: ["Docker", "Kubernetes"],
    likes: 28,
    liked: false,
    comments: [],
    timestamp: "12 hours ago",
  },
  {
    id: 9,
    username: "Chris99",
    profileImage: "https://via.placeholder.com/50",
    text: "Deploying a #ReactApp on Vercel! 🚀",
    image: "https://via.placeholder.com/500",
    hashtags: ["ReactApp", "Vercel"],
    likes: 15,
    liked: false,
    comments: [],
    timestamp: "14 hours ago",
  },
  {
    id: 10,
    username: "CodeMaster",
    profileImage: "https://via.placeholder.com/50",
    text: "The best state management for #React? Context API or Redux? 🤔",
    image: "",
    hashtags: ["React", "Redux", "ContextAPI"],
    likes: 22,
    liked: false,
    comments: [],
    timestamp: "16 hours ago",
  },
  {
    id: 11,
    username: "MiaDev",
    profileImage: "https://via.placeholder.com/50",
    text: "Just tried out #ShadCN for UI components! Amazing!",
    image: "",
    hashtags: ["ShadCN", "UI"],
    likes: 19,
    liked: false,
    comments: [],
    timestamp: "18 hours ago",
  },
  {
    id: 12,
    username: "FrontendGuy",
    profileImage: "https://via.placeholder.com/50",
    text: "Do you prefer #CSSModules or #StyledComponents? Let's discuss!",
    image: "",
    hashtags: ["CSSModules", "StyledComponents"],
    likes: 10,
    liked: false,
    comments: [],
    timestamp: "20 hours ago",
  },
  {
    id: 13,
    username: "SecurityNerd",
    profileImage: "https://via.placeholder.com/50",
    text: "Security first! Always sanitize your inputs! #CyberSecurity",
    image: "",
    hashtags: ["CyberSecurity"],
    likes: 40,
    liked: false,
    comments: [],
    timestamp: "22 hours ago",
  },
  {
    id: 14,
    username: "EmmaJS",
    profileImage: "https://via.placeholder.com/50",
    text: "What’s your favorite #React component library? 🤔",
    image: "",
    hashtags: ["React"],
    likes: 26,
    liked: false,
    comments: [],
    timestamp: "1 day ago",
  },
  {
    id: 15,
    username: "Pythonista",
    profileImage: "https://via.placeholder.com/50",
    text: "Python's #Django or #Flask? Which one do you use? 🐍",
    image: "",
    hashtags: ["Django", "Flask"],
    likes: 32,
    liked: false,
    comments: [],
    timestamp: "1 day ago",
  },
];
